"""empty message

Revision ID: 88a7bd2519d6
Revises: 834b1a697901
Create Date: 2019-10-05 18:18:04.272458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a7bd2519d6'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('company_ceo', sa.String(length=140), nullable=True),
    sa.Column('business_type', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.DateTime(), nullable=True),
    sa.Column('q1_earnings', sa.Float(), nullable=True),
    sa.Column('q2_earnings', sa.Float(), nullable=True),
    sa.Column('q3_earnings', sa.Float(), nullable=True),
    sa.Column('q4_earnings', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_year'), 'finance', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_year'), table_name='finance')
    op.drop_table('finance')
    op.drop_table('company')
    # ### end Alembic commands ###
